### ISSUE TITLE
sounds.playerMeow not working in spigot 1.9

### ISSUE THREAD

**Issue by tjhgit** [walterhiggins/ScriptCraft#291]
Caused by: sun.org.mozilla.javascript.JavaScriptException: JavaException: javax.script.ScriptException: sun.org.mozilla.javascript.EcmaError: TypeError: Cannot find function catMeow in object [object Object]. (<Unknown source>#6) in <Unknown source> at line number 6 (<Unknown source>#638)

**Comment by walterhiggins** [comment]
Hi @tjhgit ,

Sorry about that. Spigot 1.9 changed all of the Sounds Enum values. You'll need to use the following instead...
```javascript
sounds.entityCatAmbient( player );
```
