### ISSUE TITLE
Drone.extend() error

### ISSUE THREAD

**Issue by Markus-1974** [walterhiggins/ScriptCraft#438]
Hi, 

I am using scriptcraft with Minecraft spigot for MC 1.15.2

Since then there is some kind of error in scriptcraft:

[19:03:21 INFO]: [scriptcraft] Enabling scriptcraft v3.4.0-2019-01-20
[19:03:21 WARN]: Warning: Nashorn engine is planned to be removed from a future JDK release
[19:03:27 INFO]: [scriptcraft] Drone using CraftEvil.setTypeIdAndData method
[19:03:27 ERROR]: [scriptcraft] Plugin /usr/local/minecraft/spigotmc/1.15.2/scriptcraft/plugins/arrows.js Error: Error executing module /usr/local/minecraft/spigotmc/1.15.2/scriptcraft/plugins/arrows.js line #336 : Error executing module drone line #undefined : java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_15_R1.util.CraftEvil
 undefined
> undefined

[19:03:28 ERROR]: [scriptcraft] Plugin /usr/local/minecraft/spigotmc/1.15.2/scriptcraft/plugins/drone/contrib/chessboard.js Error: Error executing module /usr/local/minecraft/spigotmc/1.15.2/scriptcraft/plugins/drone/contrib/chessboard.js line #35 : Drone.extend is not a function
 ***/
> Drone.extend('chessboard', function(whiteBlock, blackBlock, width, depth) {
   var i;

[19:03:28 ERROR]: [scriptcraft] Plugin /usr/local/minecraft/spigotmc/1.15.2/scriptcraft/plugins/drone/contrib/spawn.js Error: Error executing module /usr/local/minecraft/spigotmc/1.15.2/scriptcraft/plugins/drone/contrib/spawn.js line #8 : Drone.extend is not a function
 }
> Drone.extend(spawn);
 

[19:03:28 ERROR]: [scriptcraft] Plugin /usr/local/minecraft/spigotmc/1.15.2/scriptcraft/plugins/drone/contrib/dancefloor.js Error: Error executing module /usr/local/minecraft/spigotmc/1.15.2/scriptcraft/plugins/drone/contrib/dancefloor.js line #71 : Drone.extend is not a function
 }
> Drone.extend(dancefloor);
 

[19:03:28 ERROR]: [scriptcraft] Plugin /usr/local/minecraft/spigotmc/1.15.2/scriptcraft/plugins/drone/contrib/temple.js Error: Error executing module /usr/local/minecraft/spigotmc/1.15.2/scriptcraft/plugins/drone/contrib/temple.js line #55 : Drone.extend is not a function
 }
> Drone.extend(temple);
 

[19:03:28 ERROR]: [scriptcraft] Plugin /usr/local/minecraft/spigotmc/1.15.2/scriptcraft/plugins/drone/contrib/redstonewire.js Error: Error executing module /usr/local/minecraft/spigotmc/1.15.2/scriptcraft/plugins/drone/contrib/redstonewire.js line #26 : Drone.extend is not a function
 
> Drone.extend('wireblock', function(blockType) {
   this.chkpt('wireblock')

[19:03:28 ERROR]: [scriptcraft] Plugin /usr/local/minecraft/spigotmc/1.15.2/scriptcraft/plugins/drone/contrib/hangtorch.js Error: Error executing module /usr/local/minecraft/spigotmc/1.15.2/scriptcraft/plugins/drone/contrib/hangtorch.js line #66 : Drone.extend is not a function
 }
> Drone.extend(hangtorch);
 

[19:03:28 ERROR]: [scriptcraft] Plugin /usr/local/minecraft/spigotmc/1.15.2/scriptcraft/plugins/drone/contrib/mazegen.js Error: Error executing module /usr/local/minecraft/spigotmc/1.15.2/scriptcraft/plugins/drone/contrib/mazegen.js line #36 : Drone.extend is not a function
 // Example: Try /js maze(5,7)
> Drone.extend(function maze(width, length) {
   if (typeof width === 'undefined') {

[19:03:28 ERROR]: [scriptcraft] Plugin /usr/local/minecraft/spigotmc/1.15.2/scriptcraft/plugins/drone/contrib/logo.js Error: Error executing module /usr/local/minecraft/spigotmc/1.15.2/scriptcraft/plugins/drone/contrib/logo.js line #274 : Drone.extend is not a function
 }
> Drone.extend(logojs);
 Drone.extend(logojscube);

[19:03:28 ERROR]: [scriptcraft] Plugin /usr/local/minecraft/spigotmc/1.15.2/scriptcraft/plugins/drone/contrib/lcd-clock.js Error: Error executing module /usr/local/minecraft/spigotmc/1.15.2/scriptcraft/plugins/drone/contrib/lcd-clock.js line #104 : Drone.extend is not a function
 
> Drone.extend(lcdclock);
 

[19:03:29 ERROR]: [scriptcraft] Plugin /usr/local/minecraft/spigotmc/1.15.2/scriptcraft/plugins/drone/contrib/spiral_stairs.js Error: Error executing module /usr/local/minecraft/spigotmc/1.15.2/scriptcraft/plugins/drone/contrib/spiral_stairs.js line #52 : Drone.extend is not a function
 }
> Drone.extend(spiral_stairs);
 

[19:03:29 ERROR]: [scriptcraft] Plugin /usr/local/minecraft/spigotmc/1.15.2/scriptcraft/plugins/drone/contrib/rainbow.js Error: Error executing module /usr/local/minecraft/spigotmc/1.15.2/scriptcraft/plugins/drone/contrib/rainbow.js line #63 : Drone.extend is not a function
 }
> Drone.extend(rainbow);
 

[19:03:29 ERROR]: [scriptcraft] Plugin /usr/local/minecraft/spigotmc/1.15.2/scriptcraft/plugins/drone/contrib/fort.js Error: Error executing module /usr/local/minecraft/spigotmc/1.15.2/scriptcraft/plugins/drone/contrib/fort.js line #120 : Drone.extend is not a function
 }
> Drone.extend(fort);
 

[19:03:29 ERROR]: [scriptcraft] Plugin /usr/local/minecraft/spigotmc/1.15.2/scriptcraft/plugins/drone/contrib/castle.js Error: Error executing module /usr/local/minecraft/spigotmc/1.15.2/scriptcraft/plugins/drone/contrib/castle.js line #79 : Drone.extend is not a function
 }
> Drone.extend(castle);
 

[19:03:29 ERROR]: [scriptcraft] Plugin /usr/local/minecraft/spigotmc/1.15.2/scriptcraft/plugins/drone/contrib/cottage.js Error: Error executing module /usr/local/minecraft/spigotmc/1.15.2/scriptcraft/plugins/drone/contrib/cottage.js line #158 : Drone.extend is not a function
 }
> Drone.extend(cottage_road);
 Drone.extend(cottage);

**Comment by jwulf** [comment]
Yes, see this issue: https://github.com/walterhiggins/ScriptCraft/issues/401.

Drone does not work with 1.15.2 at the moment.

**Comment by simon1974smith** [comment]
Hi,
I got exactly the same error using 1.16.5, but it is not clear to me how to resolve it??

**Comment by pniederlag** [comment]
@Markus-1974 could you maybe add some information on compatibility of scriptcraft? It would help minecraft newbies (trying to catch up with my little one) assist in pluging in things appropriatly... I have now build development with the #443 applied... on a 1.16.2 spigot server...
